version: '3'
services:
  web:
    build: .
    image: fwas
    container_name: web
    ports: 
      - "5000:5000"
    command: fwas run --debug --reload
    networks:
      ninja-network:
        aliases:
          - web
    volumes:
      - .:/app
    depends_on: 
      - redis

  worker:
    image: fwas
    container_name: fwas_worker
    command: python fwas/worker.py
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:3.2

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
    networks:
      - fwas-network

networks:
  fwas:
