version: '3'
services:
  web:
    build: .
    container_name: web
    ports: 
      - "5000:5000"
    environment:
      - FLASK_APP=fwas.app
    networks:
      ninja-network:
        aliases:
          - web

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
    networks:
      - fwas-network

networks:
  fwas:
