version: '3'

volumes:
  dbbackups:
  postgis-data:


networks:
  fwas-network:


services:
  app:
    build: .
    command: >
      uvicorn --host=0.0.0.0 --reload fwas.main:app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - fwas-network

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    networks:
      - fwas-network

  db:
    image: kartoza/postgis:11.0-2.5 
    networks:
      fwas-network:
        aliases:
          - db
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
      - ./dbbackups:/backups
      - ./config/db/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw,postgis_raster
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
